# this push works when we have ran these commands on cli
# aws configure
# aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 553662335646.dkr.ecr.ap-south-1.amazonaws.com
# run
# earthly +build --image="553662335646.dkr.ecr.ap-south-1.amazonaws.com/keycloak" --version="latest"
VERSION 0.7

origin:
    FROM registry.access.redhat.com/ubi9/openjdk-17

downloadKeycloak:
    FROM +origin
    ENV KEYCLOAK_VERSION=22.0.1
    USER root
    WAIT
        RUN set -xeu && \
            mkdir -p keycloak && \
            microdnf -y install wget tar gzip && \
            rm -rf /var/cache/yum && \
            wget https://github.com/keycloak/keycloak/releases/download/${KEYCLOAK_VERSION}/keycloak-${KEYCLOAK_VERSION}.tar.gz && \
            tar -xvf keycloak-${KEYCLOAK_VERSION}.tar.gz -C keycloak --strip-components=1 && \
            rm -rf keycloak-${KEYCLOAK_VERSION}.tar.gz
    END
    SAVE ARTIFACT keycloak

build:
    FROM +origin
    ARG image
    ARG version
    ENV KEYCLOAK_HOME /opt/keycloak/
    ENV KC_DB_NAME dev-mem
    ENV KC_DB dev-mem
    ENV KC_HOSTNAME_STRICT false
    ENV KC_HTTP_ENABLED true
    ENV KC_HEALTH_ENABLED true
    ENV KC_METRICS_ENABLED true
    ENV KC_PROXY edge
    USER root
    RUN mkdir -p ${KEYCLOAK_HOME}
    WORKDIR ${KEYCLOAK_HOME}
    COPY +downloadKeycloak/keycloak ${KEYCLOAK_HOME}
    COPY --dir script licenses ./
    RUN set -xeu && \
        microdnf -y install jq && \
        rm -rf /var/cache/yum
    RUN chmod -R 777 ${KEYCLOAK_HOME}
    EXPOSE 8080
    CMD ${KEYCLOAK_HOME}/script/entrypoint.sh
    DO +SAVE_IMAGE --name="keycloak image" --label=keycloak --image=$image --version=$version --username=keycloak

SAVE_IMAGE:
    COMMAND
    ARG image
    ARG version
    ARG label
    ARG name
    ARG username
    # git related labels
    # helps identifying the specific commit that originated the image
    ARG EARTHLY_GIT_HASH
    ARG EARTHLY_GIT_SHORT_HASH
    ARG EARTHLY_GIT_COMMIT_TIMESTAMP
    ARG EARTHLY_BUILD_SHA
    # assign labels
    LABEL $label"-hash"=$EARTHLY_GIT_HASH
    LABEL $label"-short-hash"=$EARTHLY_GIT_SHORT_HASH
    LABEL $label"-build-timestamp"=$EARTHLY_GIT_COMMIT_TIMESTAMP
    LABEL $label"-build-sha"=$EARTHLY_BUILD_SHA
    LABEL $label"-tag"=$EARTHLY_TARGET_TAG_DOCKER
    # platform labels, both target and user
    # target represents the target platform the image was built platform
    # user represents the platform where the image was built with
    ARG TARGETPLATFORM
    ARG USERPLATFORM
    # assign labels
    LABEL $label"-target-platform"=$TARGETPLATFORM
    LABEL $label"-source-platform"=$USERPLATFORM
    # always add image version as label
    LABEL $label"-version"=$version
    # add 1001 user as aip user
    IF [ ! whoami &>/dev/null ]
        RUN useradd -u 1001 -r -g 0 -d ${HOME} -s /sbin/nologin -c "specific user" ${username}
    END
    USER 1001:0
    SAVE IMAGE $image:$version

test:
    # this image helps to run command based on host privilages
    FROM earthly/dind:alpine
    ARG image
    ARG version
    WITH DOCKER --load ${image}:${version}=+build
        RUN docker run ${image}:${version}
    END