VERSION 0.7

# this push works when we have ran these commands on cli
# aws configure
# aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 553662335646.dkr.ecr.ap-south-1.amazonaws.com
# earthly --push +all --registry="553662335646.dkr.ecr.ap-south-1.amazonaws.com" --repository="kafka-ui" --tag="latest"

all:
    ARG registry
    ARG repository
    ARG tag
    BUILD +build
    BUILD +push --registry=${registry} --repository=${repository} --tag=${tag}

downloadKafkaUi:
    FROM registry.access.redhat.com/ubi8/openjdk-17
    USER root
    RUN set -xeu && \
        microdnf install wget -y && \
        rm -rf /var/cache/yum
    ENV KAFKA_UI_VERSION=v0.7.1
    RUN rm -rf ./build || true
    WORKDIR ./build
    RUN set -xeu && \
        wget https://github.com/provectus/kafka-ui/releases/download/${KAFKA_UI_VERSION}/kafka-ui-api-${KAFKA_UI_VERSION}.jar
    # save artificat in cache for other layer
    SAVE ARTIFACT kafka-ui-api-${KAFKA_UI_VERSION}.jar

build:
    FROM registry.access.redhat.com/ubi8/openjdk-17
    ENV KAFKA_UI_HOME /opt/kafka-ui
    ENV KAFKA_UI_VERSION=v0.7.1
    ENV DYNAMIC_CONFIG_ENABLED=true
    RUN mkdir -p ${KAFKA_UI_HOME}
    # use artificat in cache in this layer
    COPY +downloadKafkaUi/kafka-ui-api-${KAFKA_UI_VERSION}.jar ${KAFKA_UI_HOME}/kafka-ui-api.jar
    RUN chmod -R 777 ${KAFKA_UI_HOME}
    ENV JAVA_OPTS=
    EXPOSE 8080
    USER root
    CMD [ "/bin/sh","-c","java $JAVA_OPTS -jar /opt/kafka-ui/kafka-ui-api.jar","--add-opens","java.rmi/javax.rmi.ssl=ALL-UNNAMED" ]

push:
    FROM earthly/dind:alpine-main
    ARG registry
    ARG repository
    ARG tag
    IF [ "$registry" != "" ]
        SAVE IMAGE --push ${registry}/${repository}:${tag}
    ELSE
        SAVE IMAGE --push ${repository}:${tag}
    END